---
smrt_mac_address: "BC:07:1D:8F:AD:50"
smrt_ip_address: "10.0.10.1"  # Ziel-IP
smrt_ip_netmask: "255.255.255.0"
smrt_ip_gateway: "10.0.10.254"  # Anpassen falls nÃ¶tig

port_roles:
  management_trunk: 1
  management_access: [2]
  clients: [3, 4]
  guests: [5, 6]
  iot: [7, 8]
  # Ports 9-10 sind SFP, lassen wir erstmal weg

