---
smrt_mac_address: "8C:86:DD:AD:91:82"
smrt_ip_address: "192.168.0.1"
smrt_ip_netmask: "255.255.255.0"
smrt_ip_gateway: "192.168.0.254"

port_roles:
  management_trunk: 1
  management_access: [2]
  clients: [3, 4]
  guests: [5, 6]
  iot: [7, 8]
