---
# Ansible Connection Settings (für Custom Expect-Module nicht benötigt)
# ansible_connection: network_cli
# ansible_network_os: generic
# ansible_become: yes
# ansible_become_method: enable

# SSH Settings
ansible_ssh_common_args: '-o PubkeyAuthentication=no'

# VLAN Configuration
common_vlans:
  - id: 1
    name: "Default"
  - id: 10
    name: "Management"
  - id: 20
    name: "Clients"
  - id: 30
    name: "Guests"
  - id: 40
    name: "IoT"
