---
- hosts: switches
  name: Take ownership of TP-Link Switch
  gather_facts: no
  connection: local
  tasks:
    - name: Take ownership of the switch
      rgl.tp_link_easy_smart_switch.smrt_take_ownership:
        username: admin
        password: neinnein
        switch_ip_address: "{{ smrt_ip_address }}"
        switch_mac_address: "{{ smrt_mac_address }}"
