$ANSIBLE_VAULT;1.1;AES256
61363638646334616339386635313466633464633938633132353131393363653537383839303035
3064646362393036313063656564313033376563633139360a336364376636643364336238343661
61353264336131396637306333626138616231326565323736336239636566383138396664333063
3639666161383765640a323430663133313032386166353333343031346438663566323865376331
30383137623737653737306437623132373561366366666138643139346163393236626565383763
66313234653661396537333364396163663662636566333664353230613335376533316464353461
64646433323733306433323630306362643435633336616335633830303639333962326439313366
38366335643264613131353764646239396434643563353530353637343366386638653537373337
37303138313437313135326337303430393365623530623739663535313266666661
